meta:
    schema_name: commons.media
    autoschema: true
    model_name: TMedias
    sql_schema_dot_table: gn_commons.t_medias
    label: m√©dia
    label_field_name: title_fr
    genre: M
    unique:
        - id_table_location
        - title_fr
