type: schema
code: modules.group
title: Schema modules.group
description: DÃ©finition du schema des groupes de sous-modules

meta:
    sql_processing: true
    sql_schema_dot_table: gn_modules.t_module_groups
    label: Groupe de modules
    labels: Groupes de modules
    label_field_name: name
    genre: M
    unique:
        - code
properties:
    id_module_group:
        type: integer
        primary_key: true
        title: ID
    code:
        type: string
        title: Code du groupe de module
    name:
        type: string
        title: Nom du groupe de module
    description:
        type: string
        title: Description du groupe de module
    modules:
        type: relation
        relation_type: n-n
        title: modules
        description: Liste des modules du groupe
        schema_dot_table: gn_modules.cor_module_groupe
        schema_code: commons.module
        backref: groups
