type: schema
code: tax.taxref
title: Schema tax.taxref
description: DÃ©finition du schema de taxonomie

meta:
    autoschema: true
    model: apptax.taxonomie.models.Taxref
    genre: F
    label: taxonomie
    label_field_name: nom_vern
    unique:
        - cd_nom
