type: schema
code: user.app
title: Schema user.app
description: DÃ©finition du schema pour les applications

meta:
    model: pypnusershub.db.models.Application
    label: application
    label_field_name: nom_application
    genre: F
    unique:
        - code_application
